team-golfslag/Conflux

Conflux.API.Tests/Conflux.API.Tests.csproj, Conflux.API.Tests/ProjectDTOTests.cs, Conflux.API/Controllers/ProjectController.cs, Conflux.API/Controllers/ProjectsQueryController.cs, Conflux.API/DTOs/ProjectDTO.cs, Conflux.Data.Tests/Conflux.Data.Tests.csproj, Conflux.Data.Tests/ConfluxContextTests.cs, Conflux.Data/ConfluxContext.cs, Conflux.Data/Migrations/20250312110804_MakeProjectPartyManyToManyAndAddDates.Designer.cs, Conflux.Data/Migrations/20250312110804_MakeProjectPartyManyToManyAndAddDates.cs, Conflux.Data/Migrations/20250312124448_ChangeDateTimeToDateOnly.Designer.cs, Conflux.Data/Migrations/20250312124448_ChangeDateTimeToDateOnly.cs, Conflux.Domain/Project.cs, Conflux.sln
CX-92
This PR proposes to add an endpoint for creating a project. It adds a controller class for managing projects, and a controller in that class for creating new projects. It also adds a start and end date to the project object.
-
The field Party in Project is changed to Parties, since a project can have many parties.
=> feat: add project creation endpoint

Conflux.RepositoryConnections.NWOpen/NwOpenMapper.cs
CX-110
Fixes some small issues in the documentation of NwOpenMapper.cs
none
none
=> docs: fixes documentation NwOpenMapper

LICENSE, readme.md
De klant was akkoord gegaan met de AGPL 3.0, dus voegen we deze toe aan het project.
De uni is ook akkoord volgens de ICT handleiding.
CX-69
We voegen de AGPLv3 licentie toe. De uni en de klant waren hier mee akkoord gegaan.
geen
We moeten nog even verifiëren over mail dat dit echt mag dus nog niet mergen! 
=> chore: Voeg license toe

Conflux.API/appsettings.json, Dockerfile
CX-127
Fix docker container refusing connection and move docker file
N/A
N/A
=> build: fix docker container refusing connection and move docker file

.editorconfig, Conflux.API.Tests/Controllers/ProjectsControllerTests.cs, Conflux.API.Tests/TestWebApplicationFactory.cs, Conflux.Data.Tests/ConfluxContextTests.cs, Conflux.Data/ConfluxContext.cs, Conflux.Data/ConfluxContextFactory.cs, Conflux.Domain.Logic.Tests/DTOs/ProjectPostDTOTests.cs, Conflux.Domain.Logic.Tests/DTOs/ProjectPutDTOTests.cs, Conflux.Domain.Logic.Tests/Services/ProjectsServiceTests.cs, Conflux.Domain.Logic/DTOs/ProjectPatchDTO.cs, Conflux.Domain.Logic/DTOs/ProjectPostDTO.cs, Conflux.Domain.Logic/DTOs/ProjectPutDTO.cs, Conflux.Domain.Logic/Exceptions/ProjectNotFoundException.cs, Conflux.Domain.Logic/Services/ProjectsService.cs, Conflux.Domain/Party.cs, Conflux.Domain/Person.cs, Conflux.Domain/Product.cs, Conflux.Domain/Project.cs, Conflux.RepositoryConnections.NWOpen/NwOpenMapper.cs, Conflux.RepositoryConnections.NWOpen/SeedData.cs, Conflux.RepositoryConnections.NWOpen/TemporaryProjectRetriever.cs, Conflux.RepositoryConnections.Tests/NwOpenMapperTests.cs, Conflux.RepositoryConnections.Tests/TemporaryProjectRetriever.cs
CX-128
Add copyright headers to all files and to the editorconfig
=> chore: add copyright headers

Conflux.RepositoryConnections.NWOpen/Conflux.RepositoryConnections.NWOpen.csproj, Conflux.RepositoryConnections.NWOpen/TemporaryProjectRetriever.cs, Conflux.RepositoryConnections.Tests/Conflux.RepositoryConnections.Tests.csproj
Bump version of NWOpen.Net to 1.1.0 to fix some issues with nullable fields.
=> chore(deps): bump NWOpen.Net to 1.1.0

.github/workflows/build-and-test.yml, .github/workflows/publish-docker.yml
CX-142
We want to release a Docker image whenever main is updated so the server environment can be more easily updated.
I've also renamed the "end-to-end" pipeline, which was incorrect. When this PR is merged, we will have to make sure the repo RuleSets reflect this change.
=> ci: add docker pipeline and rename build pipeline

Conflux.API.Tests/Controllers/PeopleControllerTests.cs, Conflux.API/Controllers/PeopleController.cs, Conflux.Domain.Logic/Services/PeopleService.cs
CX-143
Added API endpoint for getting a list of people based on a query.
N.A.
N.A.
=> feat: get people by query endpoint added

.github/workflows/publish-typescript-client.yml
This was needed to make the webserver run.
CX-145
=> fix: Add dummy database to the typescript api client action.

.github/workflows/publish-typescript-client.yml
This should fix the error in the workflow.
CX-145
=> fix: Change the way we pass the connection string.

.github/workflows/publish-typescript-client.yml, Conflux.API/Program.cs, Conflux.Data.Tests/ConnectionStringHelperTests.cs, Conflux.Data/ConfluxContextFactory.cs, Conflux.Data/ConnectionStringHelper.cs
=> Feat: typescript api client

.github/workflows/publish-typescript-client.yml
=> fix: split the install of dotnet tools in publish typescript workflow

.github/workflows/publish-typescript-client.yml, Conflux.API/appsettings.Workflow.json
This is needed because dotnet ef ignores the ConnectionStrings__Database env variable.
CX-145
=> fix: add appsettings.Workflow.json for typescript client workflow

.github/workflows/publish-typescript-client.yml
We have to do this because ASPNETCORE_ENVIRONMENT gets ignored by the webserver for some reason 😭
CX-145
=> fix: add extra DOTNET_ENVIRONMENT in typescript client workflow

.github/workflows/publish-typescript-client.yml, Conflux.API/Program.cs, Conflux.API/appsettings.Development.json, Conflux.API/appsettings.Testing.json, Conflux.API/appsettings.Workflow.json, docfx.json, docs/FeatureFlags.md, docs/index.md, docs/toc.yml, index.md
CX-150
Add feature flags instead of checking if the environment is develop.
none
=> feat: Add support for feature flags

.github/workflows/publish-typescript-client.yml, backend-client/.npmrc
=> fix: fix the .npmrc file hopefully

.github/workflows/publish-typescript-client.yml
=> fix: Now add the NPM token also for the backend client workflow.

backend-client/.npmrc
We did not have the correct scope
CX-145
=> fix: Really fix the npmrc now

backend-client/.npmrc, backend-client/package.json
We still did not have the correct scope
CX-145
=> fix: Really really fix the npmrc now

backend-client/package.json
We do this so that semantic-release will only publish once.
CX-145
=> fix: Set the publishConfig in the backend client workflow

.github/workflows/publish-typescript-client.yml
This should fix the error we are getting.
CX-145
=> fix: put some env variables in the publishing job

.github/workflows/publish-typescript-client.yml
=> fix: it's environment not env

Conflux.API/Controllers/PeopleController.cs, Conflux.API/Controllers/ProjectsController.cs, Conflux.Domain.Logic/DTOs/ProjectPutDTO.cs
CX-170
We made some fields optional in the API and fixed a type checking bug.
A new version of the typescript client will be generated.
`Ok` should not be used in controllers anymore.
=> fix: required fields project put

Conflux.API.Tests/Controllers/ProjectsControllerTests.cs, Conflux.API/Controllers/ProjectsController.cs, Conflux.Domain.Logic/Conflux.Domain.Logic.csproj, Conflux.Domain.Logic/DTOs/ProjectQueryDTO.cs, Conflux.Domain.Logic/Services/ProjectsService.cs
CX-207
Implements sorting (or ordering) of query results. Also creates a dedicated DTO that contains the query, any filters, and the ordering method.
none
none
=> feat: sorteren op zoekpagina

Conflux.API/Controllers/ContributorsController.cs
CX-213
I renamed a single method
Auto generated docs change.
Geert is attracted to well structured excel spreadsheets.
It is done
=> fix: renamed method to reflect actual functionality.

Conflux.API.Tests/Controllers/OrcidControllerTest.cs, Conflux.API/Controllers/OrcidController.cs, Conflux.API/Controllers/ProjectsController.cs, Conflux.API/Program.cs, Conflux.API/appsettings.Development.json, Conflux.API/appsettings.Testing.json, Conflux.API/appsettings.Workflow.json, Conflux.API/appsettings.json, Conflux.Domain.Logic/Services/UserSessionService.cs, Conflux.Domain/Session/UserSession.cs
CX-179
This pull request introduces ORCID integration to the application, along with several related updates to the authentication flow, configuration, and middleware setup. Key changes include the addition of an `OrcidController` for managing ORCID linking/unlinking, updates to the authentication configuration to support ORCID, and adjustments to the development and production settings.
* Added `OrcidController` to handle ORCID linking, unlinking, and redirection logic, including validation of redirect URIs and database updates for ORCID IDs. 
* Introduced `AddOrcidAuth` method to configure OAuth authentication for ORCID, including cookie settings, claim mapping, and event handling for ticket creation and redirection.
* Configured `ForwardedHeadersOptions` for handling reverse proxy …
=> feat: add orcid controller and dev config

Conflux.API.Tests/Controllers/ProjectsControllerTests.cs, Conflux.API/Controllers/ContributorsController.cs, Conflux.API/Controllers/ProjectsController.cs, Conflux.Domain.Logic.Tests/DTOs/ProjectDTOTests.cs, Conflux.Domain.Logic.Tests/Services/ContributorServiceTests.cs, Conflux.Domain.Logic.Tests/Services/ProjectsServiceTests.cs, Conflux.Domain.Logic/DTOs/ContributorDTO.cs, Conflux.Domain.Logic/DTOs/ProductDTO.cs, Conflux.Domain.Logic/DTOs/ProjectDTO.cs, Conflux.Domain.Logic/Services/ContributorsService.cs, Conflux.Domain.Logic/Services/IContributorsService.cs, Conflux.Domain.Logic/Services/ProjectsService.cs
Use dtos for contributor and project in their respective services and return them from the api endpoints to make them nicer to use in the frontend.
=> feat: add nice dtos for contributor and project

Conflux.API/Controllers/ContributorsController.cs, Conflux.Domain.Logic/Services/ProjectsService.cs
CX-154
- Fix ContributorService DI
- Fix user to UserDTO mapping
=> Fix some api issues

Conflux.API/Controllers/ContributorsController.cs, Conflux.API/Program.cs, Conflux.API/appsettings.Development.json, Conflux.Domain.Logic/Exceptions/ContributorAlreadyExistsException.cs, Conflux.Domain.Logic/Services/ContributorsService.cs, Conflux.Domain.Logic/Services/IContributorsService.cs, Conflux.Domain.Logic/Services/ProjectsService.cs
CX-154
Improve performance and add contributor deletion endpoint.
=> feat: new endpoints

Conflux.API/Controllers/ProjectsController.cs, Conflux.API/Controllers/UserSessionController.cs, Conflux.API/appsettings.Development.json, Conflux.Data/Migrations/20250609141524_AddUserFavoriteAndRecentlyAccesedProjects.Designer.cs, Conflux.Data/Migrations/20250609141524_AddUserFavoriteAndRecentlyAccesedProjects.cs, Conflux.Domain.Logic.Tests/Services/ProjectsServiceTests.cs, Conflux.Domain.Logic/DTOs/Responses/UserResponseDTO.cs, Conflux.Domain.Logic/Services/IProjectsService.cs, Conflux.Domain.Logic/Services/ProjectsService.cs, Conflux.Domain/User.cs
CX-307
add favorite and recently accessed projects to the user
=> feat: add favorite and recently accessed projects to the user

Conflux.Domain.Logic/Services/ProjectsService.cs, Conflux.Domain/Project.cs
and add a comment to clarify OwnerOrganisation
[Add the ID of the YouTrack tasks that are related to this PR] \
[Example: CX-19]
=> fix: make it so that superadmins can actually be SUPER!

Conflux.Domain/Product.cs, Conflux.Integrations.RAiD.Tests/ProjectMapperServiceTests.cs
Small changes to make sure we comply with the surf raid spec.
=> fix: change schema uris to comply with surf raid spec

.github/workflows/build-and-test.yml, Conflux.API.Tests/Conflux.API.Tests.csproj, Conflux.API/Conflux.API.csproj, Conflux.Data.Tests/Conflux.Data.Tests.csproj, Conflux.Data.Tests/ConfluxContextTests.cs, Conflux.Data/Conflux.Data.csproj, Conflux.Domain.Logic.Tests/Conflux.Domain.Logic.Tests.csproj, Conflux.Domain.Logic.Tests/Services/AdminServiceTests.cs, Conflux.Domain.Logic.Tests/Services/ContributorServiceTests.cs, Conflux.Domain.Logic.Tests/Services/ProductsServiceTests.cs, Conflux.Domain.Logic.Tests/Services/ProjectOrganisationServiceTests.cs, Conflux.Domain.Logic.Tests/Services/ProjectTitlesServiceTests.cs, Conflux.Domain.Logic.Tests/Services/ProjectsServiceTests.cs, Conflux.Domain.Logic.Tests/Services/RaidInfoServiceTest.cs, Conflux.Domain.Logic.Tests/Services/SRAMProjectSyncServiceTests.cs, Conflux.Domain.Logic.Tests/Services/TimelineServiceTests.cs, Conflux.Domain.Logic/Conflux.Domain.Logic.csproj, Conflux.Domain/Conflux.Domain.csproj, Conflux.Integrations.NWOpen.Tests/Conflux.Integrations.NWOpen.Tests.csproj, Conflux.Integrations.RAiD.Tests/Conflux.Integrations.RAiD.Tests.csproj, Conflux.Integrations.SRAM.Tests/Conflux.Integrations.SRAM.Tests.csproj
CX-323
- Instead of using test containers, we now exclusively use in memory dbs for testing.
=> ci: optmize testing pipeline

.github/workflows/build-and-test.yml, Conflux.API.Tests/Controllers/ProductsControllerTests.cs, Conflux.API/Conflux.API.csproj, Conflux.API/Controllers/ProductsController.cs, Conflux.API/Program.cs, Conflux.Domain.Logic.Tests/Services/ProductsServiceTests.cs, Conflux.Domain.Logic/Conflux.Domain.Logic.csproj, Conflux.Domain.Logic/DTOs/Responses/ProductResponseDTO.cs, Conflux.Domain.Logic/Services/IProductsService.cs, Conflux.Domain.Logic/Services/ProductsService.cs
CX-324
- add an endpoint which can get information from a doi using the crossref api
=> feat: doi info endpoint
